[server]
port = 3000
bind = "0.0.0.0"

[server.auth]
username = "user"
password = "password"

[provider.vps8]
enable = true
username = "***"
password = "***"

[provider.dnshe]
enable = true
apiKey = "***"
apiSecret = "***"
